// compare-vue/src/App.vue
<template>
  <div id="app">
    <div class="navbar has-shadow">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item">MyCompany</a>
        </div>

        <span class="navbar-burger" v-on:click="toggleNav" v-bind:class="{ 'is-active': isActive}">
          <span></span>
          <span></span>
          <span></span>
        </span>


        <div class="navbar-end navbar-menu" v-bind:class="{ 'is-active': isActive}">

          <router-link to="/" class="navbar-item r-item"> Home </router-link>
          <router-link to="faq" class="navbar-item r-item"> Features </router-link>
          <router-link to="faq" class="navbar-item r-item"> About </router-link>
          <router-link to="faq" class="navbar-item r-item"> FAQ </router-link>

          <div class="navbar-item">
            <p class="control">
              <a class="button is-primary is-outlined">
                <span class="icon">
                  <i class="fa fa-download"></i>
                </span>
                <span>Join Now</span>
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>

    <router-view></router-view>

    <footer class="footer is-primary">
      <div class="container">
        <div class="columns">
          <div class="column">
            <p>And this right here is a spiffy footer, where you can put stuff</p>
          </div>
          <div class="column has-text-right">
            <a class="icon" href="#"><i class="fa fa-facebook"></i></a>
            <a class="icon" href="#"><i class="fa fa-twitter"></i></a>

          </div>
        </div>
      </div>
    </footer>
  </div>
</template>

<script>
export default {
  name: "app",
  data: function() {
    return {
      isActive: false
    };
  },
  methods: {
    toggleNav: function() {
      this.isActive = !this.isActive;
    }
  }
};
</script>

<style lang="sass">
@import '../node_modules/bulma/bulma.sass'
@import 'mq'

.navbar
  background-color: #383838
  a:hover
    coler: gray

.navbar-brand a
  color: #fff
  font-weight: bold

a.r-item
  color: #C1C1C1
  padding: 0.5rem 1.75rem
  +mobile
    color: gray
    &:hover
      background-color: #F1F1F1

.navbar-burger span
  background-color: #C1C1C1


footer
  background-color: $primary !important
  color: #fff

  .icon
    color: #fff
    margin-left: 20px

</style>

// compare-angular/src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.sass"]
})
export class AppComponent {
  toggleNav: false;
}

<div class="navbar has-shadow">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item">MyCompany</a>
    </div>

    <span class="navbar-burger" (click)="toggleNav = !toggleNav;" [ngClass]="{'is-active': toggleNav}">
      <span></span>
      <span></span>
      <span></span>
    </span>


    <div class="navbar-end navbar-menu" [ngClass]="{'is-active': toggleNav}">

      <a routerLink="/" class="navbar-item r-item"> Home </a>
      <a class="navbar-item r-item">About</a>
      <a class="navbar-item r-item">Features</a>
      <a routerLink="/faq" class="navbar-item r-item"> FAQ </a>

      <div class="navbar-item">
        <p class="control">
          <a class="button is-primary is-outlined">
            <span class="icon">
              <i class="fa fa-download"></i>
            </span>
            <span>Join Now</span>
          </a>
        </p>
      </div>
    </div>
  </div>
</div>

<router-outlet></router-outlet>

<footer class="footer is-primary">
  <div class="container">
    <div class="columns">
      <div class="column">
        <p>And this right here is a spiffy footer, where you can put stuff</p>
      </div>
      <div class="column has-text-right">
        <a class="icon" href="#">
          <i class="fa fa-facebook"></i>
        </a>
        <a class="icon" href="#">
          <i class="fa fa-twitter"></i>
        </a>

      </div>
    </div>
  </div>
</footer>
