// compare-vue/src/components/Faq.vue
<template>
  <div class="faq">
    <div class="container">
      <section class="section">
        <h1 class="title">FAQ</h1>
        <h2 class="subtitle">Lorum ipsum and all of that jazz.</h2>

        <div class="columns" v-if="faqs && faqs.length">
            <div class="column is-one-third" v-for="faq of faqs">
              <div class="card">
                <div class="card-content">
                  <p class="title">{{faq.title}}</p>
                  <p class="answer">{{faq.body}}</p>
                </div>
              </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "faq",
  data: () => ({
    faqs: [],
    errors: []
  }),

  created() {
    axios
      .get("http://jsonplaceholder.typicode.com/posts")
      .then(response => {
        this.faqs = response.data.slice(0, 10);
      })
      .catch(e => {
        this.errors.push(e);
      });
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="sass" scoped>
@import '../mq'

.pd
  padding: 2.5em 0 1.5em 0

.answer
  margin-top: 10px !important
  color: gray

.columns
  flex-wrap: wrap
</style>

// compare-angular/src/app/faq/faq.component.ts
import { Component, OnInit } from "@angular/core";
import { Http } from "@angular/http";
import "rxjs/add/operator/map";

@Component({
  selector: "app-faq",
  templateUrl: "./faq.component.html",
  styleUrls: ["./faq.component.sass"]
})
export class FaqComponent implements OnInit {
  faqs: Array<any>;

  constructor(private http: Http) {
    this.http
      .get("https://jsonplaceholder.typicode.com/posts")
      .map(response => response.json())
      .subscribe(res => (this.faqs = res));
  }

  ngOnInit() {}
}

<div class="container">
  <section class="section">
    <h1 class="title">FAQ</h1>
    <h2 class="subtitle is-4">Lorum ipsum and all of that jazz.</h2>

    <div class="columns">
      <div class="column is-one-third" *ngFor="let faq of (faqs ? faqs.slice(0,10): [])">
        <div class="card">
          <div class="card-content">
            <p class="title">{{faq.title}}</p>
            <p class="answer">{{faq.body}}</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
